apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-server
  labels:
    app: calculator-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-server
  template:
    metadata:
      labels:
        app: calculator-server
    spec:
      containers:
      - name: calculator-server
        image: letsdotech/calculator-server:v1.0.5
        ports:
        - containerPort: 8080
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-server
spec:
  type: NodePort
  selector:
    app: calculator-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001 